<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HshDetectionEngin.Licensing</AssemblyName>
    <RootNamespace>HshDetectionEngin.Licensing</RootNamespace>
  </PropertyGroup>
</Project>
