<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseSystemDrawing>true</UseSystemDrawing>
    <AssemblyName>HshDetectionEngin.Abstractions</AssemblyName>
    <RootNamespace>HshDetectionEngin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
</Project>
