<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HshDetectionEngin.LicenseIssuer</AssemblyName>
    <RootNamespace>HshDetectionEngin.LicenseIssuer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HshDetectionEngin.Licensing\HshDetectionEngin.Licensing.csproj" />
  </ItemGroup>
</Project>
