import type { CameraSettings, CameraStatus, Capability, DetectionEvent, FaceDatabaseHealth, FaceIdentity, FaceSample, FaceSimilarityPair, LiveOverlaySnapshot, ModelInfo, ServiceStatus, SettingsResponse, TriggerDefinition, WebRtcAnswer } from './types'
const apiKey = import.meta.env.VITE_HSH_API_KEY as string | undefined
async function request<T>(path: string, init?: RequestInit): Promise<T> { const headers = new Headers(init?.headers); if (init?.body && !(init.body instanceof FormData) && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json'); if (apiKey) headers.set('X-Hsh-Api-Key', apiKey); const response = await fetch(path, { ...init, headers }); if (!response.ok) { let message = `${response.status} ${response.statusText}`; try { const payload = await response.json() as { message?: string; error?: string }; message = payload.message ?? payload.error ?? message } catch { /* status is enough */ } throw new Error(message) } if (response.status === 204) return undefined as T; const body = await response.text(); return body.trim() ? JSON.parse(body) as T : undefined as T }
export const api = {
  status: () => request<ServiceStatus>('/api/v1/service/status'), capabilities: () => request<Capability[]>('/api/v1/service/capabilities'), models: () => request<ModelInfo[]>('/api/v1/service/models'), settings: () => request<SettingsResponse>('/api/v1/settings'), saveSettings: (body: { revision: number; detection?: SettingsResponse['detection']; service?: SettingsResponse['service'] }) => request<{ revision: number }>('/api/v1/settings', { method: 'PUT', body: JSON.stringify(body) }), reload: () => request<void>('/api/v1/service/reload', { method: 'POST' }),
  cameras: () => request<CameraStatus[]>('/api/v1/cameras'), camera: (id: string) => request<CameraSettings>(`/api/v1/cameras/${encodeURIComponent(id)}`), saveCamera: (camera: CameraSettings) => request<CameraSettings>(`/api/v1/cameras/${encodeURIComponent(camera.id)}`, { method: 'PUT', body: JSON.stringify(camera) }), createCamera: (camera: Partial<CameraSettings>) => request<CameraSettings>('/api/v1/cameras', { method: 'POST', body: JSON.stringify(camera) }), deleteCamera: (id: string) => request<void>(`/api/v1/cameras/${encodeURIComponent(id)}`, { method: 'DELETE' }), cameraAction: (id: string, action: 'start' | 'stop' | 'restart') => request<void>(`/api/v1/cameras/${encodeURIComponent(id)}/${action}`, { method: 'POST' }), snapshotUrl: (id: string) => `/api/v1/streams/${encodeURIComponent(id)}/snapshot?ts=${Date.now()}`, overlay: (id: string) => request<LiveOverlaySnapshot>(`/api/v1/streams/${encodeURIComponent(id)}/overlay?ts=${Date.now()}`),
  people: () => request<FaceIdentity[]>('/api/v1/face/people'), createPerson: (name: string) => request<FaceIdentity>('/api/v1/face/people', { method: 'POST', body: JSON.stringify({ name }) }), renamePerson: (id: string, name: string) => request<void>(`/api/v1/face/people/${id}`, { method: 'PATCH', body: JSON.stringify({ name }) }), deletePerson: (id: string) => request<void>(`/api/v1/face/people/${id}`, { method: 'DELETE' }), samples: (personId: string) => request<FaceSample[]>(`/api/v1/face/people/${personId}/samples`), uploadSample: (personId: string, file: File) => { const form = new FormData(); form.append('file', file); return request<FaceSample>(`/api/v1/face/people/${personId}/samples`, { method: 'POST', body: form }) }, deleteSample: (id: string) => request<void>(`/api/v1/face/samples/${id}`, { method: 'DELETE' }), moveSample: (id: string, targetPersonId: string) => request<void>(`/api/v1/face/samples/${id}/move`, { method: 'POST', body: JSON.stringify({ targetPersonId }) }), mergePeople: (target: string, source: string) => request<void>(`/api/v1/face/people/${target}/merge/${source}`, { method: 'POST' }), sampleImageUrl: (id: string) => `/api/v1/face/samples/${id}/image`, similar: (minimumSimilarity: number, onlyDifferentPeople: boolean) => request<FaceSimilarityPair[]>(`/api/v1/face/similar?minimumSimilarity=${minimumSimilarity}&onlyDifferentPeople=${onlyDifferentPeople}`), faceHealth: () => request<FaceDatabaseHealth>('/api/v1/face/database/health'), backupFaceDb: () => request<{ path: string; sizeBytes: number }>('/api/v1/face/database/backup'),
  events: (query = '') => request<DetectionEvent[]>(`/api/v1/events?limit=2000${query}`), event: (id: string) => request<DetectionEvent>(`/api/v1/events/${id}`), triggers: () => request<{ revision: number; items: TriggerDefinition[] }>('/api/v1/triggers'), createTrigger: (trigger: TriggerDefinition) => request<TriggerDefinition>('/api/v1/triggers', { method: 'POST', body: JSON.stringify(trigger) }), updateTrigger: (trigger: TriggerDefinition) => request<TriggerDefinition>(`/api/v1/triggers/${trigger.id}`, { method: 'PATCH', body: JSON.stringify(trigger) }), deleteTrigger: (id: string) => request<void>(`/api/v1/triggers/${id}`, { method: 'DELETE' }),
  webRtcOffer: (cameraId: string, body: { type: string; sdp: string }) => request<WebRtcAnswer>(`/api/v1/streams/${cameraId}/webrtc/offer`, { method: 'POST', body: JSON.stringify(body) }), closeWebRtc: (sessionId: string) => request<void>(`/api/v1/streams/webrtc/${sessionId}`, { method: 'DELETE' }),
  whep: (cameraId: string, viewerId: string, method: 'POST' | 'PATCH' | 'DELETE', sdp?: string) => {
    const headers = new Headers({ Accept: 'application/sdp' });
    if (apiKey) headers.set('X-Hsh-Api-Key', apiKey);
    if (sdp !== undefined) headers.set('Content-Type', method === 'PATCH' ? 'application/trickle-ice-sdpfrag' : 'application/sdp');
    return fetch(`/api/v1/streams/${encodeURIComponent(cameraId)}/webrtc/whep/${encodeURIComponent(viewerId)}`, { method, headers, body: sdp });
  },
}
